[package]
name = "scalcy"
version = "0.1.2"
authors = ["Simcra"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.7"

[build-dependencies]
slint-build = "1.7"
